### PR TITLE
Fix issue #177: Transform reasoning to thinking blocks when using tools

### LINKED ISSUE #177: Claude Sonnet 4 Thinking Mode incompatible with tool use - "Expected thinking or redacted_thinking, but found text" error
# Claude 4 Thinking Mode incompatible with tool use - "Expected thinking or redacted_thinking, but found text" error

## **Problem Description**

When using Claude 4 models (e.g., `anthropic/claude-sonnet-4`) with AI SDK 5 and OpenRouter provider, enabling thinking mode alongside tool use results in API errors. The provider sends `"type": "reasoning.text"` in `reasoning_details`, but Anthropic's API expects `"type": "thinking"` when thinking mode is enabled.

## **Environment**
- **AI SDK Version**: 5.0.28  
- **OpenRouter Provider Version**: @openrouter/ai-sdk-provider@1.2.0
- **Model**: anthropic/claude-sonnet-4
- **Framework**: Any (Next.js, Node.js, etc.)

## **Error Message**
```json
{
  "error": {
    "message": "Provider returned error",
    "code": 400,
    "metadata": {
      "raw": "{\"type\":\"error\",\"error\":{\"type\":\"invalid_request_error\",\"message\":\"messages.1.content.0.type: Expected `thinking` or `redacted_thinking`, but found `text`. When `thinking` is enabled, a final `assistant` message must start with a thinking block (preceeding the lastmost set of `tool_use` and `tool_result` blocks). We recommend you include thinking blocks from previous turns. To avoid this requirement, disable `thinking`.\"}}"
    }
  }
}
```

## **Steps to Reproduce**

1. Configure OpenRouter provider with Claude 4 and reasoning enabled:
```javascript
import { createOpenRouter } from '@openrouter/ai-sdk-provider';
import { streamText } from 'ai';

const openrouter = createOpenRouter({
  apiKey: 'your-api-key',
  extraBody: {
    reasoning: {
      exclude: false,
      max_tokens: 3500,
    },
  },
});

const model = openrouter('anthropic/claude-sonnet-4');
```

2. Use with tools:
```javascript
await streamText({
  model,
  messages: [{ role: 'user', content: 'Use tools and think about it' }],
  tools: {
    someFunction: {
      description: 'A test function',
      parameters: z.object({
        query: z.string()
      }),
      execute: async ({ query }) => `Result: ${query}`
    }
  }
});
```

3. Error occurs when Claude attempts to use tools while thinking is enabled.

### **Current (Incorrect) Message Structure**
The AI SDK provider currently sends:
```json
{
  "role": "assistant", 
  "content": "text response",
  "tool_calls": [...],
  "reasoning": "reasoning text",
  "reasoning_details": [
    {
      "type": "reasoning.text", // Wrong type
      "text": "thinking content"
    }
  ]
}
```

### **Required (Correct) Message Structure**
According to Anthropic's API, when thinking is enabled with tools, the message should be:
```json
{
  "role": "assistant",
  "content": [
    {
      "type": "thinking", // Correct type
      "thinking": "thinking content"
    },
    {
      "type": "text",
      "text": "text response"
    }
  ],
  "tool_calls": [...]
}
```

### **Key Issues**
1. **Wrong content type**: `"reasoning.text"` should be `"thinking"`
2. **Message structure**: When thinking is enabled, `content` must be an array starting with thinking blocks

## **Workaround Solution**

A temporary fix can be implemented by intercepting and transforming the request before it reaches Anthropic's API. The transformation needs to:

- Convert `reasoning_details` with `"type": "reasoning.text"` to proper `thinking` blocks
- Restructure the message `content` to be an array with thinking blocks first

This allows Claude 4's extended thinking to work properly with tool use until the provider is updated.

## **Possible Expected Fix**

The OpenRouter AI SDK provider maybe should:

1. **Transform reasoning content types**: Convert `"reasoning.text"` to `"thinking"` when sending to Anthropic
2. **Restructure message format**: Ensure `content` is an array with thinking blocks first when thinking is enabled

## **Related Issues & Documentation**

- **Similar issue**: #162
- **Anthropic Documentation**: [[Extended Thinking with Tool Use](https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking#extended-thinking-with-tool-use)](https://docs.anthropic.com/en/docs/build-with-claude/extended-thinking#extended-thinking-with-tool-use)

## **Impact**

This issue affects all users trying to use Claude 4's extended thinking capabilities with tool use, a key feature for building sophisticated AI agents. Currently, users must choose between thinking mode OR tools, but not both.

## **What I've Tried and Worked**

I successfully implemented a workaround by modifying the `postToApi` function in `@openrouter/ai-sdk-provider@1.2.0/dist/index.js` around line ~751 where the request body transformation occurs.

The modification intercepts requests to Claude models and transforms the message structure before sending to Anthropic's API:

```javascript
var postToApi = async ({
  url,
  headers = {},
  body,
  successfulResponseHandler,
  failedResponseHandler,
  abortSignal,
  fetch = getOriginalFetch2()
}) => {
  try {
    // Fix for Claude 4 thinking mode + tools error
    let modifiedContent = body.content;
    
    if (typeof body.content === 'string') {
      try {
        const parsedBody = JSON.parse(body.content);
        
        // Check if this is a Claude request with reasoning_details
        if (parsedBody.model && parsedBody.model.includes('claude') && parsedBody.messages) {
          let hasModifications = false;
          
          // Transform reasoning_details to proper thinking blocks
          parsedBody.messages = parsedBody.messages.map(message => {
            if (message.role === 'assistant' && message.reasoning_details) {
              hasModifications = true;
              
              // Convert reasoning_details to thinking blocks
              const thinkingBlocks = message.reasoning_details.map(detail => {
                if (detail.type === 'reasoning.text') {
                  return {
                    type: 'thinking',
                    thinking: detail.text
                  };
                }
                return detail;
              });
              
              // Restructure the message content to put thinking blocks first
              const content = [];
              
              // Add thinking blocks first
              thinkingBlocks.forEach(block => {
                content.push(block);
              });
              
              // Add any existing content that's not reasoning
              if (message.content && Array.isArray(message.content)) {
                message.content.forEach(item => {
                  if (item.type !== 'reasoning.text') {
                    content.push(item);
                  }
                });
              } else if (message.content && typeof message.content === 'string') {
                content.push({
                  type: 'text',
                  text: message.content
                });
              }
              
              // Return message with thinking blocks in content, but keep tool_calls at root level
              return {
                role: message.role,
                content: content,
                ...(message.tool_calls && { tool_calls: message.tool_calls }),
              };
            }
            return message;
          });
          
          if (hasModifications) {
            modifiedContent = JSON.stringify(parsedBody);
          }
        }
        
      } catch (parseError) {
        console.log('Could not parse body as JSON, sending as-is');
      }
    }

    const response = await fetch(url, {
      method: "POST",
      headers: removeUndefinedEntries(headers),
      body: modifiedContent,
      signal: abortSignal
    });
    
    // ... rest of existing function unchanged
  } catch (error) {
    throw handleFetchError({ error, url, requestBodyValues: body.values });
  }
};
```

### **Key Changes Made:**

1. **Transform reasoning_details**: Convert `"type": "reasoning.text"` to `"type": "thinking"`
2. **Restructure content array**: Ensure thinking blocks appear first in the content array
3. **Preserve tool_calls**: Keep tool_calls at the message root level (not moved into content)
4. **Conditional modification**: Only apply transformations when Claude models with reasoning_details are detected

### PR DESCRIPTION
**Pull request by mattapperson**
## Problem

When using Claude Sonnet 4 with extended thinking mode alongside tool use, the API returned an error:

```
"Expected `thinking` or `redacted_thinking`, but found `text`. When `thinking` is enabled, 
a final `assistant` message must start with a thinking block"
```

This occurred because Anthropic's API requires a specific message format when both features are used together.

## Root Cause

The provider was sending `reasoning_details` with type `"reasoning.text"` in a flat message structure, but Anthropic's Claude 4 API requires:

1. Message `content` as an array (not a string)
2. Thinking blocks with type `"thinking"` (not `"reasoning.text"`)
3. Thinking blocks must appear first in the content array, before text/tool_use blocks

## Solution

This PR implements conditional transformation of reasoning details to thinking blocks when both reasoning and tool calls are present:

**When both reasoning and tools are used:**
```json
{
  "role": "assistant",
  "content": [
    {"type": "thinking", "thinking": "reasoning text"},
    {"type": "text", "text": "response text"}
  ],
  "tool_calls": [...]
}
```

**When only reasoning or only tools (backward compatible):**
```json
{
  "role": "assistant",
  "content": "text",
  "reasoning_details": [{"type": "reasoning.text", "text": "..."}]
}
```

## Backward Compatibility

This fix maintains full backward compatibility:
- Messages with only reasoning use the existing format
- Messages with only tool calls use the existing format
- Only messages with BOTH reasoning AND tool calls use the new thinking block format

## Related

Closes #177

### CODE REVIEW

**Review by louisgv — APPROVED** [review]
LGTM!

File: src/chat/convert-to-openrouter-chat-messages.ts [hunk 1]
```diff
@@ -186,6 +186,10 @@ export function convertToOpenRouterChatMessages(
               reasoningDetails.push({
                 type: ReasoningDetailType.Text,
                 text: part.text,
+                id: null,
+                format: ReasoningFormat.AnthropicClaudeV1,
```
Comment (louisgv) [inline src/chat/convert-to-openrouter-chat-messages.ts]: This one is still a bit dangerous, because we need to also send reasoning back to other format as well

File: src/chat/convert-to-openrouter-chat-messages.ts [hunk 2]
```diff
@@ -199,13 +192,22 @@ export function convertToOpenRouterChatMessages(
           }
         }
 
+        // Check if we have preserved reasoning_details from the original OpenRouter response
+        // OpenRouter requires reasoning_details to be passed back unmodified for multi-turn conversations
+        // If we don't have the preserved version (AI SDK doesn't pass providerOptions back),
+        // we should NOT send reconstructed reasoning_details as they won't match the original
+        // Instead, only use the legacy reasoning field
+        const preservedReasoningDetails = (providerOptions?.openrouter as { reasoning_details?: ReasoningDetailUnion[] } | undefined)?.reasoning_details;
```
Comment (louisgv) [inline src/chat/convert-to-openrouter-chat-messages.ts]: nit: can we use a zod schema for this (instead of typecast)

File: src/chat/index.ts [hunk 3]
```diff
@@ -382,6 +383,10 @@ export class OpenRouterChatLanguageModel implements LanguageModelV2 {
                 response.usage?.cost_details?.upstream_inference_cost ?? 0,
             },
           },
+        } as {
+          provider: string;
+          reasoning_details: ReasoningDetailUnion[];
+          usage: OpenRouterUsageAccounting;
```
Comment (louisgv) [inline src/chat/index.ts]: We should add this type into the provider metadata schema instead, I think it's satisfied against a type
