### PR TITLE
fix: always use array content for system messages with block-level cache control

### LINKED ISSUE #389: Anthropic prompt caching not applied when `system` is a string in AI SDK (`ModelMessage[]`); only block content works
### Description

When using Anthropic (Claude) models via an AI SDK that uses `ModelMessage[]`, **prompt caching does not work if the `system` message is provided as a plain string and `cache_control` is attached at the message level**.  

Caching **only works** when:

- The `system` (or `user`) message `content` is an **array of text blocks**, and  
- `cache_control` is set **on a specific text block**.

This behavior is inconsistent with what developers typically expect from the AI SDK interface and with Anthropic’s documented prompt caching behavior, where cache metadata must be attached to content blocks, not bare strings.

---

#### 1. Non-working case: `system` as string + message-level cache control

```ts
const messages: ModelMessage[] = [
  {
    role: "system",
    content: "Very long system prompt (e.g. 2k+ tokens) that should be cached",
    // ❌ This style of cache control does NOT lead to Anthropic prompt caching
    providerOptions: {
      anthropic: {
        cacheControl: { type: "ephemeral" },
      },
    },
  },
  {
    role: "user",
    content: "Please answer this question based on the above system prompt.",
  },
];
```

**Observed behavior:**

- No cache-related usage fields (e.g. `cache_creation_input_tokens`, `cache_read_input_tokens`) ever appear or they stay at `0`.
- The large system prompt is re-sent and billed in full on every request.

### PR DESCRIPTION
**Pull request by robert-j-y**
## Description

Fixes #389

System messages now always use array content format, with `cache_control` placed exclusively on content blocks (never at the message level). This eliminates the `string | Array` union and prevents any possibility of `cache_control` duplication between message and block levels.

**Before:**
```json
{ "role": "system", "content": "...", "cache_control": { "type": "ephemeral" } }
```

**After (with cache control):**
```json
{ "role": "system", "content": [{ "type": "text", "text": "...", "cache_control": { "type": "ephemeral" } }] }
```

**After (without cache control):**
```json
{ "role": "system", "content": [{ "type": "text", "text": "..." }] }
```

### Key changes:
1. **Type change** (`src/types/openrouter-chat-completions-input.ts`): `ChatCompletionSystemMessageParam.content` is now `Array<ChatCompletionContentPartText>` (no string union). Removed message-level `cache_control` field entirely.
2. **Logic change** (`src/chat/convert-to-openrouter-chat-messages.ts`): System content always converts to array format. `cache_control` is conditionally spread onto the block only when present.
3. **E2E test** (`e2e/issues/issue-389-system-cache-control.test.ts`): Verifies cache write/read behavior with system message cache control.

### Cache control audit (no duplication)

| Message type | cache_control location | Duplication? |
|---|---|---|
| system | Block-level only | No |
| user (single text) | Block-level only | No |
| user (multi-part) | Block-level only (last text part) | No |
| assistant | Message-level only (string content) | No |
| tool | Message-level only (string content) | No |

### Validation
- Verified via live API tests that always-array format works across Anthropic, OpenAI, and Google Gemini
- Confirmed block-level `cache_control` is the canonical Anthropic pattern per [their docs](https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching)
- `ChatCompletionSystemMessageParam` is not exported publicly — type change is internal only

### Human review checklist
- [ ] Verify always-array system content doesn't break any downstream consumers you're aware of
- [ ] Confirm the spread pattern `...(cacheControl && { cache_control: cacheControl })` correctly omits `cache_control` when undefined
- [ ] Check that no `cache_control` appears at both message and block level for any message type

## Checklist

- [x] I have run `pnpm stylecheck` and `pnpm typecheck`
- [x] I have run `pnpm test` and all tests pass
- [x] I have added tests for my changes (if applicable)
- [ ] I have updated documentation (if applicable)

### Changeset

- [x] I have run `pnpm changeset` to create a changeset file

---

Link to Devin run: https://app.devin.ai/sessions/ac3d2be5447d40518a2b0ecac907e315
Requested by: @robert-j-y

### CODE REVIEW

File: src/types/openrouter-chat-completions-input.ts [hunk 1]
```diff
@@ -14,7 +14,7 @@ export type ChatCompletionMessageParam =
 
 export interface ChatCompletionSystemMessageParam {
   role: 'system';
-  content: string;
+  content: string | Array<ChatCompletionContentPartText>;
```
Comment (louisgv) [inline src/types/openrouter-chat-completions-input.ts]: I'd argue to rid this union and just use an array for this
