### PR TITLE
fix: preserve structured multimodal content in tool results (#181)

### LINKED ISSUE #181: tool response for image not working
```typescript
import { stepCountIs, streamText, tool } from "ai";
import { createOpenRouter } from "@openrouter/ai-sdk-provider";
import { z } from "zod";

 // a flower jpeg picture
const image = "/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAFgAXAMBIgACEQEDEQH/xAAcAAACAgMBAQAAAAAAAAAAAAAABwUGAQMECAL/xAA9EAABAwMBBgMFBAcJAAAAAAABAgMEAAURBhITITFBgQdRYSJxkbHBFDJCoSMzUoKy4fAVFkNTYnKS0fH/xAAaAQACAwEBAAAAAAAAAAAAAAAEBQABAwIG/8QAJREAAgIBBAICAgMAAAAAAAAAAQIAAxEEEiExBUETURQiYXHw/9oADAMBAAIRAxEAPwB40UUVJIVhSgkEqIAHEk1moLVk3cQRHQrDkg7P7vX5gd6onAzO60NjhR7lfud9mzJLgiPONR+SAg4JA6k+tYsl4mRJ8VmQ8tyO4rdFKznZJIwc++uBaSgN7JwDnP0+dboyg87GPDaTIb/jFCfIxbMemmsV7dvEY9FYzUXctQ2u27QkSkFxP+E37S8+4cu9FkgDJiFUZzhRmStFUC4eIamxmLBSE9C8vJPYf91GwvEycmRm4QmHI/HIjgpWPLmSDWX5FecZhY8dqCM7Y0aK5rbOjXKE1MhuBxl0ZSofI+R9K6a2gZBBwYUUUVJUKXurrjvL+4yOUZCUe8kbR+Y+FMKktrdb0HV9wStJAWpLrZz95JSOPxBHasriQsY+MVWuOfqS7zyCskcU4Sseg5fM1st6ybuw11MhH8Qqss3PLSknOMcPdz+Yqb0w6mRqZDrhG7YQ5JcJPIJ/nihhyRG1i7a2/qWzVd+U06qBEWUkD9MsHBGfwj61QJK0beSAnkK2SZxcLjrqv0rqtpRJ6nifnVfuk5SnMNKUkk8PMZ9POuLiXOZekpFSYE3TZALm6HMc/SuUJJBIHAda+I7aW8bSSeRI2s571vdfykJSAlI6Y4UPC4y/Ce4ret0q3LSNmKoLQocyFlRIPcH4+lX2l54VWdbaH7u+had6N0xngFI5lWOoJAwfQ0w6aUZ+MZnl9dt/IbbKfqjxAtun5xgFl2XKSkFaWikJbzyCiTzxxxioRvxbilX6a0vJT5pfCj8hS51S63J1RdXo6VhpUtzG0ePBRBPuyDXClAP4ie9YNc2eI0q8dSawWHMdlr8SdPz3A2tx6KsnA36Bj4pJ/Otev9P/AN4YDFztJQ/IYBADagd82egPUg8R3pMKZCuRJPuzUtp3UF40/JC4UnLR++w6SUK94+vOr+XIw0o+P+Ng9J5H3NzMVbmBghQ5gip2KwtmPLDYIelMBlOOidoKP5AjvUsbhDv6ky2oSIstX6xaF5CvPIxz9fnXJOYXGQ7JeWVMsgK9kEEHNYMSp4MtrWsOwjEg3rbJSypagpRHM9KgVsLL53gKQOlNFttxi3JkuqQ6CM7OPZIpdXq6B6UVFhtoAnCWwfqTUbr+ZtprmZiD6myFBfmrwzu0IzhTrzgbbT71Hh250ytL6FtcdLcua+3cXh7Sdg5ZSfd+Lv8ACk6Z4zwa+NYYuUmFKTKt0h2K+k5C2jg9/Mehrmt1Q8id6im21cI+P99z04BgYHSs1R9D6/hXmK1FushqNdB7JCyEpfPQpPLJ/Z+lXfNMlYMMiebtqeptrjmee9YwEQ9UXONHb3aEPkpQkcEhQCsD/lUOltQ5/On7qLSNq1AoOy21tSQMfaGSAvHkcgg9xVDvXhpcogLtreRNTn9WQG1j4nB+IoR6XByI/wBL5ChkVXODKIgDrtj96tu7CsEIAHmeZrqk2q4w3tzJgSWnfJTR4+vrWx23yoUP7ZOjussqOyneJKC4fJIPE9uFZgH3DmZOwRJDSu8/tFplptbqlnASkZzVnu0+NEjuBxxtYypIKT1HDuKobOqLlHjuRrQyzE3idlyQlO06U9QFH7o9wz619Swt/TsNBUdtteFZ68T8ax1GP0A+4DbQzvuPA6jCtq1X6yuN2wpUuMhILOfvA55Hz4f+Up7pvPtjqHAoFKiClScEehHQ1cPB2U5H1a9EKju5EVeU/wCpJBH5bVMjVGirRqPLshCmJeMCSxgK/eHJXftijBXvXPuCfKNJcUbozz2eBrFWzU2gb1Yip1DRnxP86Mgkp/3I4kdsj1qpgg8qDdWU/tG9dqWLlDmBAIwRkeRpw+GEy/S9OLJeLzbchTbSn07ZCQlPAHaBwDmllpuwTtR3EQrelO0E7bjizhLac4yfjy616F0/aI9is8a2xSS2ynG0eBWSclRx1JJNE6ZCTu9Rb5S5AoTsyRoooo6IprfebYZW88sIbbSVLUTgJA4k15+1NqB7U12clPEiOk7LDR/CjPDueBP8qdmsYMq56YuUKDj7Q8wpKEk42z+z35d687ONPQpDkeS2pt5pZQ42rmlQ6UPeTwI48SiElj3JJtA2SBwJ4k/KsyEOJYAS5lW3nJ4YHlXI1II5nNYkSsjngYAz/X9caGBj4gS0+FgK9dMkfhYdUfhj6inlS/8AC3SUmztv3S6NbuZITsNtE8W2+B4+RJxw6ADrmmBRlSkLzPK6+1bLiV6hUHddI2C7PF6fa2HHjzcSChSveUkE96nKK0IB7gqsynKnEirHp21WAPJtMXcB4guDbUrJAwPvE1K0UVAAOBKZixyTkwoooq5UKqGs9CwNRl2YhS2Llu9lDoV7KiAdkKHlx5jjwHGiiqKhhgzuuxq23IcGKGTpe+w5aYj9pl75RATu2itJz5KTkfnw64ppaA0I3ZkouF2bSu5kewgkKTHHkOhVjmew8ziiskqVTDdRr7bawvWZewMVmiitovhRRRUkhRRRUkn/2Q==";

const openrouter = createOpenRouter({
  apiKey: "sk-or-v1-xxx",
});

// const model = openrouter("google/gemini-2.5-pro-preview");
// const model = openrouter("anthropic/claude-sonnet-4");
const model = openrouter("openai/gpt-5-nano");

const result = streamText({
  model,
  messages: [
    {
      role: "user",
      content: [
        {
          type: "text",
          text: "Describe the content of https://images.squarespace-cdn.com/content/v1/1a27d1b76698.jpg",
        },
      ],
    },
  ],
  tools: {
    webFetch: tool({
      description: `Fetch content from a web page.
  IMPORTANT: you should call this tool first if user provide a URL.

        `,
      inputSchema: z.object({
        url: z
          .string()
          .url()
          .describe("The URL to fetch content from, MUST be valid url"),
      }),
      execute: async ({ url }) => {
        console.log("fetching content from", url);
        const screenshot = image;
        return { screenshot, url };
      },
      toModelOutput(output) {
        return {
          type: "content",
          value: [
            {
              type: "media",
              mediaType: "image/jpeg",
              data: output.screenshot,
            },
          ],
        };
      },
    }),
  },
  stopWhen: stepCountIs(10),
});

const messages = [];
for await (const part of result.fullStream) {
  if (part.type === "text-start") {
    messages.push("");
  } else if (part.type === "text-end") {
    console.log(messages[messages.length - 1]);
  } else if (part.type === "text-delta") {
    messages[messages.length - 1] += part.text;
  }
  console.log(part.type);
}
console.log(await result.totalUsage);
```

got response:

I attempted to fetch the image, but I can’t view or interpret its visual content directly from this chat. If you want a description, please one of the following:

- Upload the image here (attach the file), or
- Let me try a different approach to analyze it if you can provide an image you can view here, or
- Tell me what you’re specifically looking to know (e.g., is there people, text, colors, objects), and I’ll describe based on what you share.

If you’d like, I can also try to fetch and describe any visible features (colors, composition) once I can access the image content more directly.

### PR DESCRIPTION
**Pull request by robert-j-y**
## Description

Fixes #181 — when a tool returns `output.type = "content"` with structured multimodal parts (text + images), those parts were being `JSON.stringify`'d into a single string. This prevented models from using vision on images in tool results.

**Before:** `getToolResultContent()` returned `JSON.stringify(output.value)` for `content` type → model receives a JSON blob
**After:** `getToolResultContent()` maps each content part to the OpenRouter API format → model receives structured `text` / `image_url` / `file` / `input_audio` parts

### Changes

1. **Type fix** (`openrouter-chat-completions-input.ts`): `ChatCompletionToolMessageParam.content` widened from `string` to `string | Array<ChatCompletionContentPart>` — verified against the `ToolResponseMessage` schema in the openrouter-web OpenAPI spec.

2. **Logic fix** (`convert-to-openrouter-chat-messages.ts`): New `mapToolResultContentParts()` function handles `content` output type by mapping each part:
   - `text` → `{ type: 'text' }`
   - `image-data` → `{ type: 'image_url' }` with base64 data URL
   - `image-url` → `{ type: 'image_url' }` with URL
   - `file-data` (image mediaType) → `{ type: 'image_url' }` with data URL
   - `file-data` (audio mediaType) → `{ type: 'input_audio' }` with base64 data + format via `MIME_TO_FORMAT`
   - `file-data` (other mediaType) → `{ type: 'file' }` with data URL
   - `file-url` (image extension) → `{ type: 'image_url' }` with URL
   - `file-url` (non-image / no extension) → `{ type: 'file' }` with URL and filename extracted from URL path
   - `file-id` / `image-file-id` / `custom` → `{ type: 'text' }` with JSON.stringify (no clean mapping)

3. **Type-safe implementation**: Uses a `ToolResultContentPart` type alias extracted via `Extract<LanguageModelV3ToolResultOutput, { type: 'content' }>['value'][number]` so TypeScript narrows properties through the `switch` statement — no type casts anywhere in implementation or tests. The switch is exhaustive: unmapped types (`file-id`, `image-file-id`, `custom`) have explicit cases, and a `default` branch with a `never` assertion catches any future SDK additions at compile time.

4. **`file-url` inference**: Since `file-url` parts in the SDK lack a `mediaType` field, a `looksLikeImageUrl()` helper infers type from the URL path extension (e.g. `.jpg`, `.png`, `.webp` → `image_url`; `.pdf`, no extension, etc. → `file`). A `filenameFromUrl()` helper extracts the filename from the URL path for non-image files (e.g. `https://example.com/report.pdf` → `report.pdf`; extensionless URLs → `''`).

5. **Audio handling**: `file-data` parts with `audio/*` mediaTypes are mapped to `input_audio` using `MIME_TO_FORMAT` for format normalization, consistent with the user message handler. Unsupported audio formats gracefully fall through to generic `file` type rather than throwing.

### Items for human review

- **`file-url` extension heuristic**: URLs without a recognizable image extension (including extensionless API URLs like `https://api.example.com/files/123`) default to `file` type. Verify this is the desired behavior vs. defaulting to `image_url`.
- **`file.file_data` with plain URLs**: Non-image `file-url` parts are mapped to `{ type: 'file', file: { filename, file_data: url } }` — same pattern as the user content handler (L156-168). Confirm the API accepts plain URLs in `file_data`, not just data URLs.
- **Audio fallback behavior**: Unlike `getInputAudioData()` (used for user messages) which throws on unsupported formats, the tool result audio path silently falls through to `file` type. This avoids crashing on unexpected tool outputs but means unsupported audio formats won't be flagged.
- **Audio uses `MIME_TO_FORMAT` directly** instead of `getInputAudioData()` because the tool result `file-data` part type doesn't match `LanguageModelV3FilePart`. If `getInputAudioData` logic changes in the future, the tool result path would need a separate update.
- All other output types (`text`, `json`, `error-text`, `error-json`, `execution-denied`) continue to return plain strings — no behavioral change for those.
- Changes were validated with unit tests only; no live API integration test was run.

## Checklist

- [x] I have run `pnpm stylecheck` and `pnpm typecheck`
- [x] I have run `pnpm test` and all tests pass
- [x] I have added tests for my changes (if applicable)
- [ ] I have updated documentation (if applicable)

### Changeset

- [x] I have run `pnpm changeset` to create a changeset file

Link to Devin session: https://app.devin.ai/sessions/4c70ad5005f74d00b65b5321159f914c
Requested by: @robert-j-y

---

<a href="https://app.devin.ai/review/openrouterteam/ai-sdk-provider/pull/446" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open with Devin
  </picture>
</a>

### CODE REVIEW

File: src/chat/convert-to-openrouter-chat-messages.ts [hunk 1]
```diff
@@ -320,20 +325,96 @@ export function convertToOpenRouterChatMessages(
...
+            file_data: dataUrl,
+          },
+        };
+      }
+
+      case 'file-url':
+        return {
+          type: 'image_url',
+          image_url: { url: part.url },
+        };
```
Comment (robert-j-y) [inline src/chat/convert-to-openrouter-chat-messages.ts]: 🟡 **file-url content parts always mapped to image_url, even for non-image files**

In `mapToolResultContentParts`, the `file-url` case (lines 399-403) unconditionally maps every file URL to an `image_url` content part, regardless of the file type. This is inconsistent with the `file-data` case (`src/chat/convert-to-openrouter-chat-messages.ts:376-397`) which correctly distinguishes between image and non-image media types — routing images to `image_url` and non-images (e.g., PDFs) to `file`. A `file-url` pointing to a PDF or other non-image file (e.g., `https://example.com/report.pdf`) would be incorrectly sent as `image_url` instead of `file`, potentially causing the downstream model to misinterpret or fail to process the file.

<details>
<summary>Prompt for agents</summary>

```
In src/chat/convert-to-openrouter-chat-messages.ts, the file-url case at lines 399-403 should ideally distinguish between image and non-image URLs, similar to the file-data case at lines 376-397. The file-url part type in LanguageModelV3 may include a mediaType field that could be used for this distinction. If mediaType is available, check if it starts with 'image/' and route accordingly: image URLs to image_url parts, and non-image URLs to file parts (with url as file_data and an empty filename). If mediaType is not available on file-url parts, consider inferring from the URL extension or documenting the limitation.
```

</details>


<a href="https://app.devin.ai/review/openrouterteam/ai-sdk-provider/pull/446" target="_blank">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://static.devin.ai/assets/gh-open-in-devin-review-dark.svg?v=1">
    Open in Devin Review
  </picture>
</a>


---
*Was this helpful? React with 👍 or 👎 to provide feedback.*

Comment (robert-j-y) [reply src/chat/convert-to-openrouter-chat-messages.ts]: Addressed in d32f607:

1. **`file-url` → `image_url`**: Added a comment explaining the SDK limitation — `file-url` parts have no `mediaType` field (only `url` and `providerOptions`), so we can't distinguish image vs non-image URLs. `image_url` is the right default since it's the most common tool-result use case (screenshots, fetched images) and the OpenRouter API handles it for all URL types.

2. **Optional chaining consistency**: Added defensive `part.mediaType?.startsWith('image/')` in the `file-data` case to match the pattern used in the user content handler (line 122). While `mediaType` is currently required on `file-data` tool result parts, this guards against future SDK changes.

3. **`content` type always returns array**: This is by design — `output.type === 'content'` signals structured content, so returning `ChatCompletionContentPart[]` (even for text-only) is correct. The API accepts both `string` and arrays for tool message content.

**Review by mattapperson — APPROVED** [review]
