### PR TITLE
fix: support file annotation type for file uploads

### LINKED ISSUE #201: Fix annotation schema to accept "file" type for file uploads
## Problem

The annotation validation schema only accepts `type: "url_citation"`, but OpenRouter API returns
`type: "file"` when processing file uploads (PDFs, images, etc.) with vision models. This
causes validation errors that prevent users from using file processing features.

### Error

AI_TypeValidationError: Invalid input: expected "url_citation"
path: ["choices", 0, "message", "annotations", 0, "type"]

### Root Cause

When OpenRouter processes files with models like `qwen/qwen3-235b-a22b-2507` or other
vision models using the `pdf-text` or `mistral-ocr` engines, it returns file annotations as a
cost optimization feature (see [OpenRouter docs on skipping parsing 
costs](https://openrouter.ai/docs/features/multimodal/pdfs#skip-parsing-costs)).

The current schema in `src/chat/schemas.ts` only validates `type: "url_citation"`, causing the
validation to fail when `type: "file"` is returned.

### PR DESCRIPTION
**Pull request by HashimMufti**
## Summary

Fixes validation error when using vision models with file inputs by updating annotation schemas
to accept both `"url_citation"` and `"file"` annotation types.

## Problem

OpenRouter API returns `type: "file"` annotations when processing file uploads (PDFs, images)
with vision models like `qwen/qwen3-235b-a22b-2507`, but the validation schemas only accept
`type: "url_citation"`, causing `AI_TypeValidationError`.

**Error:**
AI_TypeValidationError: Invalid input: expected "url_citation"
path: ["choices", 0, "message", "annotations", 0, "type"]

## Solution

- Updated enum to accept both `["url_citation", "file"]`
- Made `url_citation` and `file` fields optional (discriminated union based on `type`)
- Added null checks in annotation processing logic
- Fixed both non-streaming and streaming annotation schemas

## Changes

**Files modified:**
- `src/chat/schemas.ts` - Updated both annotation schemas (lines 63-79, 134-150)
- `src/chat/index.ts` - Added null checks for optional `url_citation` field (lines 341, 638)

## Testing

- ✅ All existing tests pass (69 tests in Node.js + Edge environments)
- ✅ Type checking passes
- ✅ Code formatting applied
- ✅ Build succeeds

## Backward Compatibility

This change is fully backward compatible. Existing `url_citation` annotations continue to work
as before, and new `file` annotations are now supported.

Closes #201

### CODE REVIEW

**Comment by ldriss** [comment]
any updates here??

**Comment by HashimMufti** [comment]
@jakobcastro @jakobdylanc Bumping this PR since all file uploads are failing when using this package, could you please look into this?

**Comment by subtleGradient** [comment]
Nice !! Was going to try fixing this today. Looks like ya beat me to it

**Comment by ldriss** [comment]
we need the team to be active on this last commit was 2 months and this is really holding us back

**Comment by mattapperson** [comment]
@ldriss I completely understand. Please know that at OpenRouter we are significantly increasing our investment into this provider as well as our SDK. We deeply apologize for the lag time here and are actively doing our best to begin burning down the issues and open PRs

File: src/chat/file-url-utils.ts [hunk 1]
```diff
@@ -31,9 +31,12 @@ export function getFileUrl({
...
 }
 
-export function getMediaType(dataUrl: string, defaultMediaType: string): string {
+export function getMediaType(
+  dataUrl: string,
+  defaultMediaType: string,
+): string {
   const match = dataUrl.match(/^data:([^;]+)/);
-  return match ? match[1] ?? defaultMediaType : defaultMediaType;
+  return match ? (match[1] ?? defaultMediaType) : defaultMediaType;
```
Comment (jamespsterling) [inline src/chat/file-url-utils.ts:39]: ⛏️ nit
```suggestion
  const [match] = dataUrl.match(/^data:([^;]+)/);
  return match ? (match ?? defaultMediaType) : defaultMediaType;
```

**Comment by HashimMufti** [comment]
Thanks @jamespsterling! Need another ✅ to merge

**Comment by ldriss** [comment]
Thank you so much guys

**Comment by HashimMufti** [comment]
1 workflow awaiting approval :)
image

**Comment by prime7** [comment]
please merge this ASAP.

**Comment by HashimMufti** [comment]
Fixed by #208, closed.
Cheers @subtleGradient!

**Comment by ldriss** [comment]
@HashimMufti is the merge confirmed ?

**Comment by HashimMufti** [comment]
Hi @ldriss this has been fixed in merged PR #208, my PR isn't going to merge :)

**Comment by ldriss** [comment]
@HashimMufti Yeah i still get same issue haha that weird 
   **"@openrouter/ai-sdk-provider": "1.2.1",**

in schema i still see only url_citation

Schema (Line 1353):
index.jsLines 1351-1362
annotations: import_v46.z.array(
  import_v46.z.object({
    type: import_v46.z.enum(["url_citation"]),  
    url_citation: import_v46.z.object({
      end_index: import_v46.z.number(),
      start_index: import_v46.z.number(),
      title: import_v46.z.string(),
      url: import_v46.z.string(),
      content: import_v46.z.string().optional()
    })
  })
).nullish()

**Comment by HashimMufti** [comment]
Great catch @ldriss!! The schema needs to be updated in two places, #208 has only updated it once. 

I'll update this PR and request a review, in the interim, I've patched my files as a workaround if that unblocks you :)

**Comment by ldriss** [comment]
@HashimMufti Thank you so much

**Comment by HashimMufti** [comment]
Thanks @subtleGradient! Should be solved whenever this is next released @ldriss

**Comment by ldriss** [comment]
much appreciated @HashimMufti @subtleGradient

**Comment by subtleGradient** [comment]
@HashimMufti I want you to get credit for this fix on the changelog. can you submit another PR that adds a changeset file? I tried to do it for you and it just gave ME credit instead. 

- [ ] delete .changeset/slimy-lizards-kiss.md
- [ ] run `pnpm changeset`

as soon as you do I'll merge #220 which will release a patch release to npm

**Comment by ldriss** [comment]
@HashimMufti see the above, just in case you missed it

**Comment by HashimMufti** [comment]
Ah cheers @subtleGradient @ldriss 
Will do this now, thank you! :)

**Comment by HashimMufti** [comment]
Raised #223, thanks @subtleGradient @ldriss! 🚀
